alias ll='ls -l'
alias la='ls -a'
alias lg='ls -G'
alias lal='ls -a -l'

alias ga='git add .'
alias gb='git branch'
alias gc='git checkout'
alias gcb='git checkout -b'
alias gca='git commit --amend'
alias gcp='git cherry-pick'
alias gcm='git commit -m'
alias gd='git diff'
alias gg='git grep'
alias gl='git log'
alias gpl='git pull'
alias gpo='git push origin'
alias gpoh='git push origin HEAD'
alias gr='git reset'
alias grh='git reset HEAD~'
alias gri='git rebase -i'
alias grir='git rebase -i --root'
alias grc='git rebase --continue'
alias grl='git reflog'
alias gs='git status'
alias gsh='git stash'
alias gshd='git stash drop'
alias gshl='git stash list'
alias gshp='git stash pop'
alias gcwip='git commit --allow-empty -m "WIP PR"'

alias gphm='git push heroku master'
alias hr='heroku run'
alias hrpmm='heroku run python3 manage.py migrate'

alias dasp='django-admin startproject'
alias pms='python3 manage.py startapp'
alias pmr='python3 manage.py runserver'
alias pmm='python3 manage.py migrate'
alias pmmm='python3 manage.py makemigrations'
alias pmcs='python3 manage.py createsuperuser'

alias setup='source ~/github/config/setup.sh'
alias spppt='source ~/github/config/simple-prompt.sh'
alias stppt='source ~/github/config/short-prompt.sh'
alias lgppt='source ~/github/config/long-prompt.sh'
alias hidef='source ~/github/config/hide.sh'
alias showf='source ~/github/config/show.sh'

alias vbp='vim ~/.bash_profile'
alias vbr='vim ~/.bashrc'
alias vvr='vim ~/.vimrc'

alias cdd='cd ..'
alias cdgh='cd ~/github/'
alias cdcg='cd ~/github/config/'
alias cdah='cd ~/github/arcadia19th/'
alias cdpt='cd ~/github/python/'
alias cdud='cd ~/github/Unorganized/'

alias resh='exec $SHELL -l'

alias delds='find . -name ".DS_Store" -type f -ls -delete'

